name: CI

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: ghcr.io/endorphinol/devops-pipeline-project

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build image
        run: docker build -t $IMAGE_NAME:${{ github.sha }} .
      - name: Login in GHCR
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image to registry
        run: docker push $IMAGE_NAME:{{ github.sha}}
